export const SET_TRENDING_ARTICLES = 'set_trending_articles'
export const SET_CURRENT_ARTICLE = 'set_current_article'
export const SET_CATEGORIES = 'set_categories'
export const SET_SEARCH = 'set_search'
export const WELCOME = 'welcome'
